name: Copy Docker Image to GHCR

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  copy-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Copy image from Docker Hub to GHCR
        run: |
          docker buildx imagetools create \
            --tag ghcr.io/amrex-codes/amrex:latest \
            weiqunzhang/amrex:latest
